(()=>{
const DB='phoneMuseumMediaDB',STORE='media',POSTS='phoneMuseumSocialPosts';let stream=null,rec=null,chunks=[];
const safe=s=>String(s||'').replace(/[<>]/g,'');
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function addMedia(blob,type){const db=await openDB(),id=Date.now()+'-'+Math.random().toString(36).slice(2),urlType=blob.type;await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put({id,type,blob,urlType,time:Date.now()});tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});return id}
async function allMedia(){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result.sort((a,b)=>b.time-a.time));r.onerror=()=>rej(r.error)})}
async function getMedia(id){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function stage(){return document.getElementById('stage')}
function openPanel(title,html){const s=stage();if(!s)return;s.classList.remove('hide');s.innerHTML=`<div class="panel"><h2>${title}</h2>${html}<p><button id="aeBack">GERİ</button></p></div>`;document.getElementById('aeBack').onclick=()=>{stopCam();s.classList.add('hide');s.innerHTML=''}}
function stopCam(){if(rec&&rec.state!=='inactive')try{rec.stop()}catch(e){}rec=null;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
async function camera(){openPanel('KAMERA',`<video id="camV" autoplay playsinline muted style="width:100%;aspect-ratio:3/4;object-fit:cover;background:#000;border-radius:14px"></video><div style="display:flex;gap:8px;justify-content:center;flex-wrap:wrap;margin-top:10px"><button id="photoB">FOTOĞRAF ÇEK</button><button id="videoB">VİDEO BAŞLAT</button><button id="flipB">KAMERAYI ÇEVİR</button></div><p id="camMsg"></p>`);let facing='user';async function start(){stopCam();stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing}},audio:true});document.getElementById('camV').srcObject=stream}try{await start()}catch(e){document.getElementById('camMsg').textContent='Kamera/mikrofon izni gerekli.';return}document.getElementById('photoB').onclick=async()=>{const v=document.getElementById('camV'),c=document.createElement('canvas');c.width=v.videoWidth||720;c.height=v.videoHeight||1280;c.getContext('2d').drawImage(v,0,0,c.width,c.height);c.toBlob(async b=>{await addMedia(b,'photo');document.getElementById('camMsg').textContent='Fotoğraf Galeri’ye kaydedildi.'},'image/jpeg',.9)};document.getElementById('videoB').onclick=()=>{if(rec&&rec.state==='recording'){rec.stop();return}chunks=[];rec=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('video/webm;codecs=vp8,opus')?'video/webm;codecs=vp8,opus':'video/webm'});rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=async()=>{await addMedia(new Blob(chunks,{type:rec.mimeType}),'video');document.getElementById('videoB').textContent='VİDEO BAŞLAT';document.getElementById('camMsg').textContent='Video Galeri’ye kaydedildi.'};rec.start();document.getElementById('videoB').textContent='VİDEOYU DURDUR'};document.getElementById('flipB').onclick=async()=>{facing=facing==='user'?'environment':'user';await start()}}
async function gallery(){const list=await allMedia();openPanel('GALERİ',`<div id="galGrid" style="display:grid;grid-template-columns:repeat(2,1fr);gap:8px">${list.length?'':'<p>Henüz fotoğraf veya video yok.</p>'}</div>`);const g=document.getElementById('galGrid');for(const m of list){const u=URL.createObjectURL(m.blob),d=document.createElement('div');d.style='background:#eef4f7;border-radius:12px;padding:6px';d.innerHTML=m.type==='video'?`<video src="${u}" controls playsinline style="width:100%;border-radius:9px"></video>`:`<img src="${u}" style="width:100%;border-radius:9px">`;const b=document.createElement('button');b.textContent='SOSYAL MEDYADA PAYLAŞ';b.style.marginTop='5px';b.onclick=()=>social(m.id);d.appendChild(b);g.appendChild(d)}}
function calcExpr(expr){expr=String(expr).replace(/,/g,'.').replace(/[^0-9+\-*/().%]/g,'');if(!expr)return'0';if(/\*\*|\/\/|\.\./.test(expr))throw Error();const f=Function('"use strict";return ('+expr.replace(/(\d+(?:\.\d+)?)%/g,'($1/100)')+')');const n=f();if(!Number.isFinite(n))throw Error();return String(Math.round((n+Number.EPSILON)*1e10)/1e10)}
function calculator(){openPanel('HESAP MAKİNESİ',`<input id="calcD" readonly value="0" style="width:100%;font-size:28px;text-align:right;padding:12px"><div id="calcK" style="display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin-top:10px"></div>`);let x='';const keys=['C','(',')','÷','7','8','9','×','4','5','6','-','1','2','3','+','0','.','%','='];const k=document.getElementById('calcK'),d=document.getElementById('calcD');keys.forEach(v=>{const b=document.createElement('button');b.textContent=v;b.onclick=()=>{if(v==='C')x='';else if(v==='='){try{x=calcExpr(x.replace(/×/g,'*').replace(/÷/g,'/'))}catch(e){x='Hata'}}else{if(x==='Hata')x='';x+=v}d.value=x||'0'};k.appendChild(b)})}
function posts(){try{return JSON.parse(localStorage.getItem(POSTS)||'[]')}catch(e){return[]}}
function savePosts(a){localStorage.setItem(POSTS,JSON.stringify(a.slice(-100)))}
async function social(selected=''){const list=await allMedia(),p=posts();openPanel('SOSYAL MEDYA',`<textarea id="socText" placeholder="Bir şeyler yaz..." style="width:100%;height:70px;padding:8px"></textarea><select id="socMedia" style="width:100%;padding:9px;margin:8px 0"><option value="">Medya seçme</option>${list.map(m=>`<option value="${m.id}" ${m.id===selected?'selected':''}>${m.type==='video'?'Video':'Fotoğraf'} · ${new Date(m.time).toLocaleString('tr-TR')}</option>`).join('')}</select><button id="socPost">PAYLAŞ</button><hr><div id="feed"></div>`);document.getElementById('socPost').onclick=()=>{const text=document.getElementById('socText').value.trim(),mediaId=document.getElementById('socMedia').value;if(!text&&!mediaId)return;const a=posts();a.unshift({id:Date.now(),text,mediaId,time:Date.now()});savePosts(a);social()};const feed=document.getElementById('feed');for(const post of p){const d=document.createElement('div');d.style='text-align:left;background:#eef4f7;border-radius:12px;padding:10px;margin:8px 0';d.innerHTML=`<b>0601 Kullanıcısı</b><p>${safe(post.text)}</p><small>${new Date(post.time).toLocaleString('tr-TR')}</small>`;if(post.mediaId){const m=await getMedia(post.mediaId);if(m){const u=URL.createObjectURL(m.blob),el=document.createElement(m.type==='video'?'video':'img');el.src=u;el.style='width:100%;border-radius:10px;margin-top:7px';if(m.type==='video'){el.controls=true;el.playsInline=true}d.appendChild(el)}}feed.appendChild(d)}}
function settings(){openPanel('AYARLAR',`<p><button id="setInstall">TELEFONA KUR</button></p><p><button id="setNotify">ARAMA BİLDİRİMLERİNİ AÇ</button></p><p><b>Benim Numaram</b><br>${safe(localStorage.getItem('phoneMuseumOwnNumber')||'')}</p>`);document.getElementById('setInstall').onclick=()=>parent.postMessage({type:'pm-install'},location.origin);document.getElementById('setNotify').onclick=()=>parent.postMessage({type:'pm-notify'},location.origin)}
function enhance(){document.querySelectorAll('.apps').forEach(grid=>{if(!grid.querySelector('[data-ae-social]')){const b=document.createElement('button');b.className='app';b.dataset.aeSocial='1';b.innerHTML='<span>🌐</span>Sosyal Medya';grid.appendChild(b)}})}
document.addEventListener('click',e=>{const a=e.target.closest?.('.app');if(!a)return;const t=a.textContent.trim().toLocaleLowerCase('tr-TR');if(t.includes('kamera')){e.preventDefault();e.stopPropagation();camera()}else if(t.includes('galeri')){e.preventDefault();e.stopPropagation();gallery()}else if(t.includes('hesap')){e.preventDefault();e.stopPropagation();calculator()}else if(t.includes('ayar')){e.preventDefault();e.stopPropagation();settings()}else if(t.includes('sosyal medya')){e.preventDefault();e.stopPropagation();social()}},false);
new MutationObserver(enhance).observe(document.body,{childList:true,subtree:true});setTimeout(enhance,300);
})();