(()=>{
const OWN='phoneMuseumOwnNumber',HIST='phoneMuseumRecentCalls',CONT='phoneMuseumContacts',MSG='phoneMuseumMessages';
const own=localStorage.getItem(OWN);if(!own)return;
let peer=null,ready=false,active=null,local=null,remoteEl=null;
const pid=n=>'pm-'+String(n||'').replace(/\D/g,'');
const clean=n=>String(n||'').replace(/\D/g,'');
const fmt=n=>{n=clean(n);return n.length===11?n.slice(0,4)+' '+n.slice(4,7)+' '+n.slice(7,9)+' '+n.slice(9,11):n};
const get=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch(e){return d}};
const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function hist(n,dir='outgoing',kind='voice'){n=clean(n);if(n.length!==11)return;let a=get(HIST);a.unshift({number:n,time:Date.now(),direction:dir,kind});put(HIST,a.slice(0,100));}
function msg(n,text,dir){let a=get(MSG);a.push({number:clean(n),text:String(text).slice(0,1000),direction:dir,time:Date.now()});put(MSG,a.slice(-300));}
const css=document.createElement('style');css.textContent=`#commLayer{position:fixed;inset:0;z-index:12000;background:#0b1c25ed;display:none;align-items:center;justify-content:center;padding:14px;font-family:Arial,sans-serif}#commLayer.on{display:flex}.commCard{width:min(430px,96vw);max-height:92vh;overflow:auto;background:#f8fbfd;color:#173242;border-radius:22px;padding:16px;text-align:center}.commNum{font:900 22px monospace;margin:6px}.commBtns{display:flex;gap:8px;justify-content:center;flex-wrap:wrap}.commBtns button{border:0;border-radius:13px;padding:11px 13px;font-weight:900;background:#263847;color:#fff}.ok{background:#198754!important}.bad{background:#bd3030!important}.videoStage{position:relative;width:100%;aspect-ratio:3/4;background:#000;border-radius:16px;overflow:hidden;margin:10px 0}.videoStage video{width:100%;height:100%;object-fit:cover}.localV{position:absolute!important;right:8px!important;top:8px!important;width:30%!important;height:27%!important;border:2px solid #fff;border-radius:10px}.miniBtn{margin:3px;border:0;border-radius:10px;padding:7px 10px;background:#263847;color:#fff;font-weight:900}.msgBubble{text-align:left;margin:7px 0;padding:8px 10px;border-radius:12px;background:#e6eef2}.msgBubble.out{margin-left:30px;background:#d8f1df}.rowLine{display:flex;justify-content:space-between;gap:8px;align-items:center;border-bottom:1px solid #dde6ea;padding:9px 0}`;document.head.appendChild(css);
const layer=document.createElement('div');layer.id='commLayer';layer.innerHTML='<div class="commCard"><div id="commState"><b>İLETİŞİM</b></div><div id="commNum" class="commNum"></div><div id="commBody"></div><div id="commBtns" class="commBtns"></div></div>';document.body.appendChild(layer);
const S=()=>document.getElementById('commState'),N=()=>document.getElementById('commNum'),B=()=>document.getElementById('commBody'),A=()=>document.getElementById('commBtns');
function show(s,n='',body='',buttons=''){layer.classList.add('on');S().innerHTML='<b>'+s+'</b>';N().textContent=fmt(n);B().innerHTML=body;A().innerHTML=buttons;}
function closeUI(){layer.classList.remove('on');B().innerHTML='';A().innerHTML='';}
function stopMedia(){if(local){local.getTracks().forEach(t=>t.stop());local=null}if(remoteEl){try{remoteEl.pause()}catch(e){}remoteEl.srcObject=null;remoteEl.remove();remoteEl=null}}
function cleanup(close=true){if(close&&active){try{active.close()}catch(e){}}active=null;stopMedia();closeUI()}
function waitReady(ms=8000){return new Promise((res,rej)=>{if(ready&&peer&&!peer.destroyed&&!peer.disconnected)return res();let st=Date.now(),t=setInterval(()=>{if(ready&&peer&&!peer.destroyed&&!peer.disconnected){clearInterval(t);res()}else if(Date.now()-st>ms){clearInterval(t);rej(new Error('Hat açılamadı'))}},100)})}
async function media(video){if(!navigator.mediaDevices?.getUserMedia)throw new Error('Kamera/mikrofon desteklenmiyor');return navigator.mediaDevices.getUserMedia(video?{audio:{echoCancellation:true,noiseSuppression:true},video:{facingMode:{ideal:'user'}}}:{audio:{echoCancellation:true,noiseSuppression:true},video:false})}
function bind(call,n,kind){active=call;call.on('stream',stream=>{if(kind==='video'){show('GÖRÜNTÜLÜ GÖRÜŞME',n,'<div class="videoStage"><video id="rv" autoplay playsinline></video><video id="lv" class="localV" autoplay muted playsinline></video></div>','<button id="hang" class="bad">KAPAT</button>');let rv=document.getElementById('rv'),lv=document.getElementById('lv');rv.srcObject=stream;lv.srcObject=local;rv.play().catch(()=>{});lv.play().catch(()=>{});remoteEl=rv;document.getElementById('hang').onclick=()=>cleanup(true)}else{remoteEl=document.createElement('audio');remoteEl.autoplay=true;remoteEl.playsInline=true;remoteEl.srcObject=stream;document.body.appendChild(remoteEl);remoteEl.play().catch(()=>{});show('GÖRÜŞMEDE',n,'<p>Ses bağlantısı aktif.</p>','<button id="hang" class="bad">KAPAT</button>');document.getElementById('hang').onclick=()=>cleanup(true)}});call.on('close',()=>cleanup(false));call.on('error',()=>{show('ÇAĞRI HATASI',n,'<p>Bağlantı kurulamadı.</p>','<button id="hang" class="bad">KAPAT</button>');document.getElementById('hang').onclick=()=>cleanup(false)})}
async function outgoing(target,kind){target=clean(target);if(target.length!==11||!target.startsWith('0601'))return alert('0601 ile başlayan 11 haneli numara gir.');if(target===own)return alert('Kendi numaranı arayamazsın.');hist(target,'outgoing',kind);try{show(kind==='video'?'VİDEO HATTI':'HAT BAĞLANIYOR',target,'<p>Bağlantı hazırlanıyor…</p>','<button id="cancel" class="bad">İPTAL</button>');document.getElementById('cancel').onclick=()=>cleanup(false);await waitReady();local=await media(kind==='video');show(kind==='video'?'GÖRÜNTÜLÜ ARANIYOR':'ARANIYOR',target,'<p>Karşı tarafın uygulaması açık olmalı.</p>','<button id="hang" class="bad">KAPAT</button>');document.getElementById('hang').onclick=()=>cleanup(true);const c=peer.call(pid(target),local,{metadata:{from:own,kind}});bind(c,target,kind)}catch(e){show('ARAMA BAŞLAMADI',target,'<p>'+String(e.message||e)+'</p>','<button id="hang" class="bad">KAPAT</button>');document.getElementById('hang').onclick=()=>cleanup(false)}}
function incoming(call){const n=clean(call.metadata?.from||String(call.peer).replace(/^pm-/,'')),kind=call.metadata?.kind==='video'?'video':'voice';hist(n,'incoming',kind);show(kind==='video'?'GELEN GÖRÜNTÜLÜ ARAMA':'GELEN ARAMA',n,'<p>'+(kind==='video'?'📹 Görüntülü arama':'☎ Sesli arama')+'</p>','<button id="ans" class="ok">CEVAPLA</button><button id="rej" class="bad">REDDET</button>');document.getElementById('rej').onclick=()=>{try{call.close()}catch(e){}cleanup(false)};document.getElementById('ans').onclick=async()=>{try{local=await media(kind==='video');call.answer(local);bind(call,n,kind)}catch(e){try{call.close()}catch(_){}alert('Kamera/mikrofon izni gerekli.');cleanup(false)}}}
function sendMessage(target,text){target=clean(target);text=String(text||'').trim();if(target.length!==11||!target.startsWith('0601'))return alert('Geçerli 0601 numarası gir.');if(!text)return;waitReady().then(()=>{const c=peer.connect(pid(target),{reliable:true,metadata:{from:own}});let timer=setTimeout(()=>alert('Karşı taraf çevrimdışı olabilir.'),5000);c.on('open',()=>{clearTimeout(timer);c.send({type:'message',from:own,text,time:Date.now()});msg(target,text,'out');setTimeout(()=>c.close(),200);showMessages(target)});c.on('error',()=>{})}).catch(()=>alert('Mesaj hattı hazır değil.'))}
function onData(c){const n=clean(c.metadata?.from||String(c.peer).replace(/^pm-/,''));c.on('data',d=>{if(d?.type==='message'){msg(n,d.text,'in');show('YENİ MESAJ',n,'<p>'+String(d.text).replace(/[<>]/g,'')+'</p>','<button id="openM">AÇ</button><button id="hang">KAPAT</button>');document.getElementById('openM').onclick=()=>showMessages(n);document.getElementById('hang').onclick=closeUI}})}
function showHistory(){const a=get(HIST);show('SON ARAMALAR',a.length+'','<div>'+a.map(x=>'<div class="rowLine"><div><b>'+fmt(x.number)+'</b><br><small>'+(x.direction==='incoming'?'GELEN':'GİDEN')+' · '+(x.kind==='video'?'VİDEO':'SES')+' · '+new Date(x.time).toLocaleString('tr-TR')+'</small></div><button class="miniBtn redial" data-n="'+x.number+'">ARA</button></div>').join('')+'</div>','<button id="hang">KAPAT</button>');document.getElementById('hang').onclick=closeUI;B().querySelectorAll('.redial').forEach(b=>b.onclick=()=>{closeUI();openDialWith(b.dataset.n)})}
function showMessages(target=''){const a=get(MSG),t=target?a.filter(x=>x.number===target):a.slice(-40);show('MESAJLAR',target,'<div>'+t.map(m=>'<div class="msgBubble '+(m.direction==='out'?'out':'')+'"><b>'+(m.direction==='out'?'Sen':fmt(m.number))+'</b><div>'+String(m.text).replace(/[<>]/g,'')+'</div><small>'+new Date(m.time).toLocaleString('tr-TR')+'</small></div>').join('')+'</div><input id="mto" inputmode="numeric" maxlength="11" placeholder="0601..." value="'+target+'" style="width:100%;padding:10px;margin-top:8px"><textarea id="mtx" placeholder="Mesaj" style="width:100%;height:80px;margin-top:8px;padding:10px"></textarea>','<button id="sendM" class="ok">GÖNDER</button><button id="hang">KAPAT</button>');document.getElementById('sendM').onclick=()=>sendMessage(document.getElementById('mto').value,document.getElementById('mtx').value);document.getElementById('hang').onclick=closeUI}
function openDialWith(n){document.getElementById('openPhoneBtn')?.click();setTimeout(()=>{const el=document.getElementById('num');if(el)el.textContent=n},80)}
function installButtons(){const ownEl=document.getElementById('ownNumber');if(!ownEl)return;if(!document.getElementById('recentCallsBtn')){let b=document.createElement('button');b.id='recentCallsBtn';b.className='miniBtn';b.textContent='SON ARAMALAR';b.onclick=showHistory;ownEl.insertAdjacentElement('afterend',b)}if(!document.getElementById('messagesBtn')){let b=document.createElement('button');b.id='messagesBtn';b.className='miniBtn';b.textContent='MESAJLAR';b.onclick=()=>showMessages();document.getElementById('recentCallsBtn').insertAdjacentElement('afterend',b)}}
function installDialButtons(){const call=document.getElementById('callBtn');if(!call)return;if(!document.getElementById('videoDialBtn')){let b=document.createElement('button');b.id='videoDialBtn';b.textContent='📹 VİDEO ARA';b.onclick=e=>{e.preventDefault();e.stopPropagation();const n=clean(document.getElementById('num')?.textContent);outgoing(n,'video')};call.insertAdjacentElement('afterend',b)}}
function init(){peer=new Peer(pid(own),{debug:1});peer.on('open',()=>{ready=true;installButtons();installDialButtons()});peer.on('disconnected',()=>{ready=false;try{peer.reconnect()}catch(e){}});peer.on('close',()=>ready=false);peer.on('call',incoming);peer.on('connection',onData);peer.on('error',e=>{if(e?.type==='peer-unavailable'&&active){show('ULAŞILAMIYOR','', '<p>Karşı taraf çevrimdışı veya eski sürümde.</p>','<button id="hang">KAPAT</button>');document.getElementById('hang').onclick=()=>cleanup(true)}})}
function load(){if(window.Peer)return init();let s=document.createElement('script');s.src='https://unpkg.com/peerjs@1.5.5/dist/peerjs.min.js';s.onload=init;s.onerror=()=>alert('Arama servisi yüklenemedi.');document.head.appendChild(s)}
document.addEventListener('click',e=>{const app=e.target.closest?.('.app');if(app&&app.textContent.includes('Rehber'))setTimeout(()=>{},0);if(app&&app.textContent.includes('Mesajlar')){e.preventDefault();e.stopPropagation();setTimeout(()=>showMessages(),0);return}const b=e.target.closest?.('#callBtn');if(b){const n=clean(document.getElementById('num')?.textContent);if(n.length===11&&n.startsWith('0601')){e.preventDefault();e.stopImmediatePropagation();outgoing(n,'voice')}}},true);
new MutationObserver(()=>{installButtons();installDialButtons()}).observe(document.body,{childList:true,subtree:true});
window.addEventListener('beforeunload',()=>{cleanup(true);if(peer&&!peer.destroyed)peer.destroy()});load();setTimeout(()=>{installButtons();installDialButtons()},400);
})();