(()=>{
const OWN='phoneMuseumOwnNumber',HIST='phoneMuseumRecentCalls',MSG='phoneMuseumMessages';
let own=localStorage.getItem(OWN)||'';
if(!/^0500\d{7}$/.test(own)){own='0500'+String(Math.floor(Math.random()*10000000)).padStart(7,'0');localStorage.setItem(OWN,own);location.reload();return;}
let peer=null,ready=false,active=null,local=null,remoteEl=null;
const clean=n=>String(n||'').replace(/\D/g,'');
const valid=n=>/^0500\d{7}$/.test(clean(n));
const pid=n=>'pm-'+clean(n);
const fmt=n=>{n=clean(n);return n.length===11?n.slice(0,4)+' '+n.slice(4,7)+' '+n.slice(7,9)+' '+n.slice(9,11):n};
const get=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch(e){return d}};
const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function saveHist(n,dir='outgoing',kind='voice'){n=clean(n);if(!valid(n))return;const a=get(HIST);a.unshift({number:n,time:Date.now(),direction:dir,kind});put(HIST,a.slice(0,100));}
function saveMsg(n,text,dir){const a=get(MSG);a.push({number:clean(n),text:String(text).slice(0,1000),direction:dir,time:Date.now()});put(MSG,a.slice(-300));}
const st=document.createElement('style');st.textContent=`#commLayer{position:fixed;inset:0;z-index:12000;background:#0b1c25ed;display:none;align-items:center;justify-content:center;padding:14px;font-family:Arial}#commLayer.on{display:flex}.commCard{width:min(430px,96vw);max-height:92vh;overflow:auto;background:#f8fbfd;color:#173242;border-radius:22px;padding:16px;text-align:center}.commNum{font:900 22px monospace;margin:6px}.commBtns{display:flex;gap:8px;justify-content:center;flex-wrap:wrap}.commBtns button,.miniBtn{border:0;border-radius:12px;padding:9px 11px;font-weight:900;background:#263847;color:#fff}.ok{background:#198754!important}.bad{background:#bd3030!important}.videoStage{position:relative;width:100%;aspect-ratio:3/4;background:#000;border-radius:16px;overflow:hidden;margin:10px 0}.videoStage video{width:100%;height:100%;object-fit:cover}.localV{position:absolute!important;right:8px!important;top:8px!important;width:30%!important;height:27%!important;border:2px solid #fff;border-radius:10px}.rowLine{display:flex;justify-content:space-between;gap:8px;align-items:center;border-bottom:1px solid #dde6ea;padding:9px 0}.msgBubble{text-align:left;margin:7px 0;padding:8px 10px;border-radius:12px;background:#e6eef2}.msgBubble.out{margin-left:30px;background:#d8f1df}`;document.head.appendChild(st);
const layer=document.createElement('div');layer.id='commLayer';layer.innerHTML='<div class="commCard"><div id="commState"><b>İLETİŞİM</b></div><div id="commNum" class="commNum"></div><div id="commBody"></div><div id="commBtns" class="commBtns"></div></div>';document.body.appendChild(layer);
const S=()=>document.getElementById('commState'),N=()=>document.getElementById('commNum'),B=()=>document.getElementById('commBody'),A=()=>document.getElementById('commBtns');
function show(s,n='',body='',buttons=''){layer.classList.add('on');S().innerHTML='<b>'+s+'</b>';N().textContent=fmt(n);B().innerHTML=body;A().innerHTML=buttons;}
function closeUI(){layer.classList.remove('on');B().innerHTML='';A().innerHTML='';}
function stopMedia(){if(local){local.getTracks().forEach(t=>t.stop());local=null}if(remoteEl){try{remoteEl.pause()}catch(e){}try{remoteEl.srcObject=null}catch(e){}try{remoteEl.remove()}catch(e){}remoteEl=null}}
function cleanup(doClose=true){if(doClose&&active){try{active.close()}catch(e){}}active=null;stopMedia();closeUI()}
function waitReady(ms=8000){return new Promise((res,rej)=>{if(ready&&peer&&!peer.destroyed&&!peer.disconnected)return res();const start=Date.now(),t=setInterval(()=>{if(ready&&peer&&!peer.destroyed&&!peer.disconnected){clearInterval(t);res()}else if(Date.now()-start>ms){clearInterval(t);rej(new Error('Hat açılamadı'))}},120)})}
async function media(video){if(!navigator.mediaDevices?.getUserMedia)throw new Error('Kamera/mikrofon desteklenmiyor');return navigator.mediaDevices.getUserMedia(video?{audio:true,video:{facingMode:{ideal:'user'}}}:{audio:true,video:false})}
function bind(call,n,kind){active=call;call.on('stream',stream=>{if(kind==='video'){show('GÖRÜNTÜLÜ GÖRÜŞME',n,'<div class="videoStage"><video id="rv" autoplay playsinline></video><video id="lv" class="localV" autoplay muted playsinline></video></div>','<button id="hang" class="bad">KAPAT</button>');const rv=document.getElementById('rv'),lv=document.getElementById('lv');rv.srcObject=stream;lv.srcObject=local;rv.play().catch(()=>{});lv.play().catch(()=>{});remoteEl=rv}else{remoteEl=document.createElement('audio');remoteEl.autoplay=true;remoteEl.playsInline=true;remoteEl.srcObject=stream;document.body.appendChild(remoteEl);remoteEl.play().catch(()=>{});show('GÖRÜŞMEDE',n,'<p>Ses bağlantısı aktif.</p>','<button id="hang" class="bad">KAPAT</button>')}document.getElementById('hang').onclick=()=>cleanup(true)});call.on('close',()=>cleanup(false));call.on('error',()=>{show('ÇAĞRI HATASI',n,'<p>Bağlantı kurulamadı.</p>','<button id="hang" class="bad">KAPAT</button>');document.getElementById('hang').onclick=()=>cleanup(false)})}
async function outgoing(target,kind){target=clean(target);if(!valid(target))return alert('0500 ile başlayan 11 haneli numara gir.');if(target===own)return alert('Kendi numaranı arayamazsın.');saveHist(target,'outgoing',kind);try{show(kind==='video'?'VİDEO HATTI':'HAT BAĞLANIYOR',target,'<p>Bağlantı hazırlanıyor…</p>','<button id="cancel" class="bad">İPTAL</button>');document.getElementById('cancel').onclick=()=>cleanup(false);await waitReady();local=await media(kind==='video');show(kind==='video'?'GÖRÜNTÜLÜ ARANIYOR':'ARANIYOR',target,'<p>Karşı tarafın uygulaması açık olmalı.</p>','<button id="hang" class="bad">KAPAT</button>');document.getElementById('hang').onclick=()=>cleanup(true);const c=peer.call(pid(target),local,{metadata:{from:own,kind}});bind(c,target,kind)}catch(e){show('ARAMA BAŞLAMADI',target,'<p>'+String(e.message||e)+'</p>','<button id="hang" class="bad">KAPAT</button>');document.getElementById('hang').onclick=()=>cleanup(false)}}
function incoming(call){const n=clean(call.metadata?.from||String(call.peer).replace(/^pm-/,'')),kind=call.metadata?.kind==='video'?'video':'voice';saveHist(n,'incoming',kind);show(kind==='video'?'GELEN GÖRÜNTÜLÜ ARAMA':'GELEN ARAMA',n,'<p>'+(kind==='video'?'📹 Görüntülü arama':'☎ Sesli arama')+'</p>','<button id="ans" class="ok">CEVAPLA</button><button id="rej" class="bad">REDDET</button>');document.getElementById('rej').onclick=()=>{try{call.close()}catch(e){}cleanup(false)};document.getElementById('ans').onclick=async()=>{try{local=await media(kind==='video');call.answer(local);bind(call,n,kind)}catch(e){try{call.close()}catch(_){}cleanup(false)}}}
function sendMessage(target,text){target=clean(target);text=String(text||'').trim();if(!valid(target)||!text)return alert('Geçerli bir 0500 numarası gir.');waitReady().then(()=>{const c=peer.connect(pid(target),{reliable:true,metadata:{from:own}});c.on('open',()=>{c.send({type:'message',from:own,text,time:Date.now()});saveMsg(target,text,'out');setTimeout(()=>c.close(),200);showMessages(target)})}).catch(()=>alert('Mesaj hattı hazır değil.'))}
function onData(c){const n=clean(c.metadata?.from||String(c.peer).replace(/^pm-/,''));c.on('data',d=>{if(d?.type==='message'){saveMsg(n,d.text,'in');show('YENİ MESAJ',n,'<p>'+String(d.text).replace(/[<>]/g,'')+'</p>','<button id="openM">AÇ</button><button id="hang">KAPAT</button>');document.getElementById('openM').onclick=()=>showMessages(n);document.getElementById('hang').onclick=closeUI}})}
function showHistory(){const a=get(HIST).filter(x=>valid(x.number));show('SON ARAMALAR',String(a.length),'<div>'+a.map(x=>'<div class="rowLine"><div><b>'+fmt(x.number)+'</b><br><small>'+(x.direction==='incoming'?'GELEN':'GİDEN')+' · '+(x.kind==='video'?'VİDEO':'SES')+' · '+new Date(x.time).toLocaleString('tr-TR')+'</small></div><button class="miniBtn redial" data-n="'+x.number+'">ARA</button></div>').join('')+'</div>','<button id="hang">KAPAT</button>');document.getElementById('hang').onclick=closeUI;B().querySelectorAll('.redial').forEach(b=>b.onclick=()=>{closeUI();document.getElementById('openPhoneBtn')?.click();setTimeout(()=>{const n=document.getElementById('num');if(n)n.textContent=b.dataset.n},80)})}
function showMessages(target=''){const a=get(MSG).filter(x=>valid(x.number)),t=target?a.filter(x=>x.number===target):a.slice(-40);show('MESAJLAR',target,'<div>'+t.map(m=>'<div class="msgBubble '+(m.direction==='out'?'out':'')+'"><b>'+(m.direction==='out'?'Sen':fmt(m.number))+'</b><div>'+String(m.text).replace(/[<>]/g,'')+'</div><small>'+new Date(m.time).toLocaleString('tr-TR')+'</small></div>').join('')+'</div><input id="mto" inputmode="numeric" maxlength="11" placeholder="0500..." value="'+target+'" style="width:100%;padding:10px;margin-top:8px"><textarea id="mtx" placeholder="Mesaj" style="width:100%;height:80px;margin-top:8px;padding:10px"></textarea>','<button id="sendM" class="ok">GÖNDER</button><button id="hang">KAPAT</button>');document.getElementById('sendM').onclick=()=>sendMessage(document.getElementById('mto').value,document.getElementById('mtx').value);document.getElementById('hang').onclick=closeUI}
function installTopButtons(){const o=document.getElementById('ownNumber');if(!o)return;if(!document.getElementById('recentCallsBtn')){const b=document.createElement('button');b.id='recentCallsBtn';b.className='miniBtn';b.textContent='SON ARAMALAR';b.onclick=showHistory;o.insertAdjacentElement('afterend',b)}if(!document.getElementById('messagesBtn')){const b=document.createElement('button');b.id='messagesBtn';b.className='miniBtn';b.textContent='MESAJLAR';b.onclick=()=>showMessages();document.getElementById('recentCallsBtn').insertAdjacentElement('afterend',b)}}
function installDial(){const call=document.getElementById('callBtn');if(!call)return;if(!call.dataset.commBound){call.dataset.commBound='1';const old=call.onclick;call.onclick=e=>{const n=clean(document.getElementById('num')?.textContent);if(valid(n)){e.preventDefault();outgoing(n,'voice');return false}if(typeof old==='function')return old.call(call,e)}}if(!document.getElementById('videoDialBtn')){const b=document.createElement('button');b.id='videoDialBtn';b.textContent='📹 VİDEO ARA';b.onclick=()=>{const n=clean(document.getElementById('num')?.textContent);outgoing(n,'video')};call.insertAdjacentElement('afterend',b)}}
function init(){peer=new Peer(pid(own),{debug:1});peer.on('open',()=>{ready=true;installTopButtons();installDial()});peer.on('disconnected',()=>{ready=false;try{peer.reconnect()}catch(e){}});peer.on('close',()=>ready=false);peer.on('call',incoming);peer.on('connection',onData)}
function load(){if(window.Peer)return init();const s=document.createElement('script');s.src='https://unpkg.com/peerjs@1.5.5/dist/peerjs.min.js';s.onload=init;document.head.appendChild(s)}
new MutationObserver(()=>{installTopButtons();installDial()}).observe(document.body,{childList:true,subtree:true});
window.addEventListener('beforeunload',()=>{cleanup(true);if(peer&&!peer.destroyed)peer.destroy()});
load();setTimeout(()=>{installTopButtons();installDial()},400);
})();
(()=>{if(document.querySelector('script[data-app-engine]'))return;const s=document.createElement('script');s.src='apps-engine.js?v=4';s.dataset.appEngine='1';document.head.appendChild(s)})();
(()=>{if(document.querySelector('script[data-phone-fixes]'))return;const s=document.createElement('script');s.src='phone-fixes.js?v=2';s.dataset.phoneFixes='1';document.head.appendChild(s)})();