const SERPER_SEARCH='https://google.serper.dev/search';
const SERPER_IMAGES='https://google.serper.dev/images';
const RETAILERS=['trendyol.com','hepsiburada.com','amazon.com.tr','amazon.com','n11.com','pttavm.com','pazarama.com','teknosa.com','mediamarkt.com.tr','koctas.com.tr','vatanbilgisayar.com','idefix.com','boyner.com.tr','carrefoursa.com','migros.com.tr','petlebi.com','petburada.com','mamaciteyze.com','jollypet.com','bisikletcim.com','decathlon.com.tr'];
const SHORT=['ty.gl','bit.ly','t.co','tinyurl.com','amzn.to','hb.biz','cutt.ly','rb.gy','is.gd'];
const BLOCKED=['cimri.com','akakce.com','onual.com','epey.com','enuygun.com'];
const CATEGORY_RULES=[
 {name:'kedi kumu',p:/(kedi\s*kumu|cat litter)/i,variants:['topaklanan kedi kumu','bentonit kedi kumu','silika kedi kumu','doğal kedi kumu']},
 {name:'elektrikli bisiklet',p:/(elektrikli\s*bisiklet|e-bike|ebike)/i,variants:['şehir tipi elektrikli bisiklet','katlanır elektrikli bisiklet','uzun menzil elektrikli bisiklet','yüksek taşıma kapasiteli elektrikli bisiklet']},
 {name:'vantilatör',p:/(vantilatör|ayaklı fan|kule fan)/i,variants:['ayaklı vantilatör','kule tipi vantilatör','sessiz vantilatör','uzaktan kumandalı vantilatör']},
 {name:'telefon',p:/(cep telefonu|akıllı telefon|telefon)/i,variants:['fiyat performans telefon','kamerası iyi telefon','uzun pil ömürlü telefon']},
 {name:'süpürge',p:/(süpürge|vacuum)/i,variants:['dikey süpürge','robot süpürge','toz torbasız süpürge']},
 {name:'kahve makinesi',p:/(kahve makinesi|espresso makinesi)/i,variants:['türk kahvesi makinesi','espresso makinesi','tam otomatik kahve makinesi']},
 {name:'airfryer',p:/(airfryer|air fryer|yağsız fritöz)/i,variants:['airfryer','çift hazneli airfryer','büyük hacimli airfryer']}
];
function send(res,s,b){res.statusCode=s;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(b))}
function key(){return String(process.env.SERPER_API_KEY||'').trim().replace(/^["']|["']$/g,'')}
function host(u=''){try{return new URL(u).hostname.replace(/^www\./,'').toLowerCase()}catch{return''}}
function isUrl(v=''){try{return /^https?:$/.test(new URL(v).protocol)}catch{return false}}
function clean(q=''){return String(q).replace(/["'`()[\]{}+*~^]/g,' ').replace(/\b(?:OR|AND|NOT)\b/gi,' ').replace(/\s+/g,' ').trim().slice(0,180)}
function blocked(h){return BLOCKED.some(d=>h===d||h.endsWith('.'+d))}
function retailer(h){return RETAILERS.some(d=>h===d||h.endsWith('.'+d))}
function norm(v=''){return String(v).toLocaleLowerCase('tr-TR').replace(/[^a-z0-9çğıöşü]/g,'')}
function parsePrice(t=''){const s=t.replace(/\./g,'').replace(/,/g,'.');const m=s.match(/(?:₺\s*)?(\d{2,9}(?:\.\d{1,2})?)\s*(?:TL|₺)/i)||s.match(/₺\s*(\d{2,9}(?:\.\d{1,2})?)/i);return m?Number(m[1]):null}
async function serper(url,body){const k=key();if(!k)throw new Error('SERPER_API_KEY eksik.');const r=await fetch(url,{method:'POST',headers:{'X-API-KEY':k,'Content-Type':'application/json'},body:JSON.stringify({...body,q:clean(body.q)})});const raw=await r.text();let p={};try{p=JSON.parse(raw)}catch{}if(!r.ok)throw new Error(`Serper ${r.status}: ${p.message||p.error||raw.slice(0,160)}`);return p}
async function resolveShort(v){if(!isUrl(v)||!SHORT.includes(host(v)))return v;const h={'User-Agent':'Mozilla/5.0','Accept':'text/html'};for(const method of ['HEAD','GET'])try{const r=await fetch(v,{method,redirect:'follow',headers:h,signal:AbortSignal.timeout(10000)});if(r.url&&r.url!==v)return r.url}catch{}return v}
function normalize(x){const link=x.link||x.productLink||'';const title=x.title||'';const snippet=x.snippet||'';return{title,link,hostname:host(link),source:x.source||host(link),snippet,image:x.imageUrl||x.thumbnailUrl||x.thumbnail||'',priceValue:parsePrice(`${x.price||''} ${title} ${snippet}`),rating:x.rating||null,ratingCount:x.ratingCount||x.reviews||null}}
function categoryOf(q){return CATEGORY_RULES.find(x=>x.p.test(q))||null}
function identityFromUrl(u){try{const p=new URL(u).pathname.split('/').filter(Boolean).map(decodeURIComponent);const i=p.findIndex(x=>/-p-\d+/i.test(x));const slug=(i>=0?p[i]:p.at(-1)||'').replace(/-p-\d+.*/i,'').replace(/[-_]+/g,' ');const brand=i>0?p[i-1].replace(/[-_]+/g,' '):'';const model=(slug.match(/\b([A-ZÇĞİÖŞÜ]{1,10})[-\s]?([0-9]{2,6}[A-Z0-9-]*)\b/i)||[]).slice(1).join('-').toUpperCase();const cat=categoryOf(slug);return{brand,model,category:cat?.name||'',title:slug,canonical:[brand,model,cat?.name].filter(Boolean).join(' ')||slug}}catch{return{brand:'',model:'',category:'',title:u,canonical:u}}}
function identityFromText(t){const model=(t.match(/\b([A-ZÇĞİÖŞÜ]{1,10})[-\s]?([0-9]{2,6}[A-Z0-9-]*)\b/i)||[]).slice(1).join('-').toUpperCase();const cat=categoryOf(t);const words=t.trim().split(/\s+/);const brand=model?words[0]:'';return{brand,model,category:cat?.name||t.trim(),title:t.trim(),canonical:model?[brand,model,cat?.name].filter(Boolean).join(' '):t.trim()}}
function isProductPage(x){if(!x.link||blocked(x.hostname)||!retailer(x.hostname))return false;const p=(()=>{try{return new URL(x.link).pathname}catch{return''}})();return /(?:-p-\d+|\/p\/|\/urun\/|\/product\/|\/dp\/|\/ip\/|\/pd\/)/i.test(p)||p.split('/').filter(Boolean).length>=3}
function sameCategory(x,cat){if(!cat)return true;return cat.p.test(`${x.title} ${x.snippet}`)}
function productKey(x){return norm(x.title.replace(/\b\d+[.,]?\d*\s*(?:tl|₺)\b/gi,'').split(/[-|]/)[0].slice(0,80))}
function facts(text=''){const g=(r,s='')=>{const m=text.match(r);return m?m[1]+s:''};return{power:g(/\b(\d{2,4})\s*(?:w|watt)\b/i,' W'),range:g(/\b(\d{2,3})\s*km\b/i,' km'),battery:g(/\b(\d{2,4})\s*(?:wh|ah|v)\b/i),weight:g(/\b(\d{1,3})\s*kg\b/i,' kg'),volume:g(/\b(\d+(?:[.,]\d+)?)\s*(?:lt|l|litre)\b/i,' L'),warranty:g(/\b(\d+)\s*yıl\s*garanti\b/i,' yıl'),rating:(text.match(/([1-5](?:[.,]\d)?)\s*(?:\/5|puan|yıldız)/i)||[])[1]||''}}
function whyFor(item,category,index){const f=facts(`${item.title} ${item.snippet}`);const reasons=[];if(item.priceValue)reasons.push(`${Math.round(item.priceValue).toLocaleString('tr-TR')} TL seviyesinde fiyat bulundu`);if(f.rating)reasons.push(`${f.rating}/5 puan sinyali var`);if(category?.name==='elektrikli bisiklet'){if(f.range)reasons.push(`${f.range} menzil belirtilmiş`);if(f.power)reasons.push(`${f.power} motor gücü var`);if(f.battery)reasons.push(`batarya bilgisi bulunuyor`)}if(category?.name==='kedi kumu'){if(/topaklan/i.test(item.title+item.snippet))reasons.push('topaklanan yapı');if(/bentonit/i.test(item.title+item.snippet))reasons.push('bentonit içerik');if(/silika/i.test(item.title+item.snippet))reasons.push('silika seçenek');if(f.volume||f.weight)reasons.push(`${f.volume||f.weight} paket`)}if(!reasons.length)reasons.push(index<3?'kategoriyle güçlü eşleşme':'farklı kullanım ihtiyacına alternatif');return reasons.slice(0,3).join(' • ')}
async function imageFor(item,cat){if(item.image)return item.image;try{const p=await serper(SERPER_IMAGES,{q:`${item.title} ${cat?.name||''}`,gl:'tr',hl:'tr',num:4});const f=(p.images||[]).find(i=>!cat||cat.p.test(`${i.title||''} ${i.source||''}`))||(p.images||[])[0];return f?.imageUrl||f?.thumbnailUrl||''}catch{return''}}
async function categorySearch(input,cat){const variants=cat?.variants||[input,`${input} en iyi`,`${input} fiyat performans`,`${input} kullanıcı yorumları`];const queries=[`${input} satın al fiyat`,...variants.slice(0,4).map(v=>`${v} satın al fiyat`),`${input} yorum inceleme`];const payloads=await Promise.all(queries.map(q=>serper(SERPER_SEARCH,{q,gl:'tr',hl:'tr',num:20}).catch(()=>({}))));let all=[];for(const p of payloads)all.push(...(p.shopping||[]).map(normalize),...(p.organic||[]).map(normalize));const seen=new Set();let products=all.filter(x=>isProductPage(x)&&sameCategory(x,cat)&&norm(x.title.split(/\s+/)[0])!=='sinbo').filter(x=>{const k=productKey(x);if(!k||seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>{const ap=Number.isFinite(a.priceValue)?1:0,bp=Number.isFinite(b.priceValue)?1:0;const ar=Number(a.rating)||0,br=Number(b.rating)||0;return bp-ap||br-ar}).slice(0,12);products=await Promise.all(products.map(async(x,i)=>({...x,image:await imageFor(x,cat),facts:facts(`${x.title} ${x.snippet}`),why:whyFor(x,cat,i),rank:i+1})));const reviewPayload=payloads.at(-1)||{};const reviews=(reviewPayload.organic||[]).map(normalize).filter(x=>x.link&&!blocked(x.hostname)).slice(0,12);const prices=products.filter(x=>Number.isFinite(x.priceValue)).sort((a,b)=>a.priceValue-b.priceValue);const advice={title:products.length>=6?'Caynana çoklu seçenek hazırladı':'Seçenekler sınırlı',summary:`${products.length} farklı ürün seçeneği ve ${new Set(products.map(x=>x.hostname)).size} doğrudan satış sitesi bulundu. Tek ürüne bağlanmadan fiyat, teknik özellik ve kullanım amacına göre karşılaştır.`,reasons:[`${products.length} farklı ürün listelendi`,`${new Set(products.map(x=>x.hostname)).size} farklı mağaza tarandı`,cat?.name==='elektrikli bisiklet'?'Menzil, motor ve batarya sinyalleri öne çıkarıldı':cat?.name==='kedi kumu'?'Topaklanma, içerik ve paket boyutu sinyalleri öne çıkarıldı':'Fiyat ve özellik sinyalleri karşılaştırıldı'],cautions:['Satıcı puanı, garanti ve teslimat koşullarını mağazada son kez kontrol et.']};return{mode:'category',input,query:input,identity:{brand:'',model:'',category:cat?.name||input,title:input,canonical:input},type:'product',technicalFacts:{},reviewSignals:{positive:[],negative:[]},advice,summary:{resultCount:products.length+reviews.length,pricedCount:prices.length,lowestPrice:prices[0]||null,highestPrice:prices.at(-1)||null,averagePrice:prices.length?Math.round(prices.reduce((s,x)=>s+x.priceValue,0)/prices.length):null},prices:prices.slice(0,18),reviews,alternatives:products,images:products.filter(x=>x.image).map(x=>({image:x.image,thumbnail:x.image,title:x.title,source:x.source,link:x.link})).slice(0,10),sources:[...reviews,...products].slice(0,20),analyzedAt:new Date().toISOString()}}
async function exactSearch(original,resolved,id){const base=id.canonical;const cat=categoryOf(base);const [p1,p2,p3,p4]=await Promise.all([serper(SERPER_SEARCH,{q:`${base} fiyat satın al`,gl:'tr',hl:'tr',num:20}),serper(SERPER_SEARCH,{q:`${base} yorum inceleme şikayet`,gl:'tr',hl:'tr',num:15}),serper(SERPER_SEARCH,{q:`${id.category||base} alternatif modeller fiyat`,gl:'tr',hl:'tr',num:20}),serper(SERPER_IMAGES,{q:base,gl:'tr',hl:'tr',num:10})]);const raw=[...(p1.shopping||[]),...(p1.organic||[])].map(normalize);const prices=raw.filter(x=>isProductPage(x)&&Number.isFinite(x.priceValue)&&(!cat||sameCategory(x,cat))).sort((a,b)=>a.priceValue-b.priceValue).slice(0,18);const reviews=(p2.organic||[]).map(normalize).filter(x=>x.link&&!blocked(x.hostname)).slice(0,12);let alternatives=[...(p3.shopping||[]),...(p3.organic||[])].map(normalize).filter(x=>isProductPage(x)&&(!cat||sameCategory(x,cat))&&norm(x.title.split(/\s+/)[0])!=='sinbo').slice(0,8);alternatives=await Promise.all(alternatives.map(async(x,i)=>({...x,image:await imageFor(x,cat),why:whyFor(x,cat,i),facts:facts(`${x.title} ${x.snippet}`)})));const images=(p4.images||[]).map(x=>({image:x.imageUrl||x.thumbnailUrl||'',thumbnail:x.thumbnailUrl||x.imageUrl||'',title:x.title||base,source:x.source||'',link:x.link||''})).filter(x=>x.image).slice(0,10);const policy=norm(id.brand)==='sinbo'?{active:true,title:'Satın alma önerilmez',message:'Güncel tüketici şikâyetleri, servis ve garanti koşulları ayrıntılı doğrulanmadan bu marka için olumlu satın alma önerisi verilmez.'}:{active:false};return{mode:'exact',input:original,resolvedInput:resolved!==original?resolved:null,query:base,identity:id,type:'product',brandPolicy:policy,technicalFacts:facts([id.title,...reviews.map(x=>x.title+' '+x.snippet)].join(' ')),reviewSignals:{positive:[],negative:[]},advice:{title:policy.active?policy.title:(prices.length>=3?'Karşılaştırılabilir':'Temkinli karşılaştır'),summary:policy.active?policy.message:(prices[0]?`${prices.length} doğrudan mağaza fiyatı bulundu. En düşük görülen fiyat ${Math.round(prices[0].priceValue).toLocaleString('tr-TR')} TL.`:'Yeterli doğrudan mağaza fiyatı bulunamadı.'),reasons:[`${prices.length} fiyat kaynağı`,`${alternatives.length} alternatif ürün`],cautions:['Satıcı, garanti ve teslimat koşullarını kontrol et.']},summary:{resultCount:prices.length+reviews.length,pricedCount:prices.length,lowestPrice:prices[0]||null,highestPrice:prices.at(-1)||null,averagePrice:prices.length?Math.round(prices.reduce((s,x)=>s+x.priceValue,0)/prices.length):null},prices,reviews,alternatives,images,sources:[...reviews,...alternatives].slice(0,20),analyzedAt:new Date().toISOString()}}
module.exports=async function handler(req,res){if(req.method!=='POST')return send(res,405,{error:'Yalnızca POST desteklenir.'});try{const b=typeof req.body==='string'?JSON.parse(req.body):(req.body||{});const original=String(b.input||b.url||'').trim();if(!original)return send(res,400,{error:'Bir bağlantı veya ürün adı girin.'});const resolved=await resolveShort(original);if(isUrl(original)&&SHORT.includes(host(original))&&resolved===original)return send(res,422,{error:'Kısa bağlantının hedefi açılamadı.'});if(!isUrl(resolved)){const cat=categoryOf(resolved);const model=/\b[A-ZÇĞİÖŞÜ]{1,10}[-\s]?\d{2,6}/i.test(resolved);if(!model)return send(res,200,await categorySearch(resolved,cat));return send(res,200,await exactSearch(original,resolved,identityFromText(resolved)))}return send(res,200,await exactSearch(original,resolved,identityFromUrl(resolved)))}catch(e){return send(res,500,{error:e.message||'Araştırma yapılamadı.'})}};